//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonateForGood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ItemPost
    {
        public ItemPost()
        {
            this.ContactByEmail = true;
            this.ContactByPhone = false;
            this.DisplayMyPhoneNo = false;
            this.DisplayMyEmail_ = false;
            this.CommentsOnRecentActivities = new HashSet<CommentsOnRecentActivity>();
            this.Kudos = new HashSet<Kudo>();
        }

        public int ItemPostId { get; set; }
        public int ItemCategoryId_ { get; set; }
        public int LocationId_ { get; set; }
        public string ItemName { get; set; }
        public string PhoneNumber { get; set; }

        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        public string EmailAddress_ { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public byte[] Photo1 { get; set; }
        public byte[] Photo2 { get; set; }
        public byte[] Photo3 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ItemStatusId { get; set; }
        public bool ContactByEmail { get; set; }
        public bool ContactByPhone { get; set; }
        public bool DisplayMyPhoneNo { get; set; }
        public bool DisplayMyEmail_ { get; set; }
        public Nullable<int> ItemCollectPreferenceId { get; set; }
        public Nullable<int> UserId { get; set; }

        public virtual ICollection<CommentsOnRecentActivity> CommentsOnRecentActivities { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemCollectPreference ItemCollectPreference { get; set; }
        public virtual Location Location { get; set; }
        public virtual ItemStatu ItemStatu { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Kudo> Kudos { get; set; }
    }
}
