//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonateForGood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CommentsOnRecentActivities = new HashSet<CommentsOnRecentActivity>();
            this.ItemPosts = new HashSet<ItemPost>();
            this.Kudos = new HashSet<Kudo>();
            this.NGODetails = new HashSet<NGODetail>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int UserId { get; set; }
        public int UserTypeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<int> SecurityQuestionID { get; set; }
    
        public virtual ICollection<CommentsOnRecentActivity> CommentsOnRecentActivities { get; set; }
        public virtual ICollection<ItemPost> ItemPosts { get; set; }
        public virtual ICollection<Kudo> Kudos { get; set; }
        public virtual ICollection<NGODetail> NGODetails { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
