//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonateForGood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Locations = new HashSet<Location>();
            this.NGODetails = new HashSet<NGODetail>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public int StateId { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<NGODetail> NGODetails { get; set; }
    }
}
