//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonateForGood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGODetail
    {
        public int NGODetailId { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
        public string WebSiteURL { get; set; }
        public string ContactNumber1 { get; set; }
        public byte[] Photo { get; set; }
        public string ContactPersonName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Zipcode { get; set; }
        public string Landmark { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
        public virtual State State { get; set; }
    }
}
